#!/bin/sh

DIR=$HOME/src/nstdio_test
cd $DIR
. ./connect_test.config

${SSH} -N -f -L ${PORT_B_SSHL}:localhost:${PORT_F_B_NSTDIO} ${USER_F}@${IP_F_B}
#PP=$?
./sqb localhost ${PORT_B_SSHL}
#kill -9 $PP
#./sqb localhost ${PORT_F_B_NSTDIO}
